import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/lib/theme-provider.lib";
import "./globals.css";
import NavigationBar from "@/components/ui/navigation-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <main className="flex w-full flex-col items-center justify-between">
            <NavigationBar />
            <div className="w-full min-h-screen">{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
